/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;

/**
 *
 * @author Chris
 */
public class Arguments extends javax.swing.JPanel {

	public javax.swing.JButton getGenerateButton() {
		return generateButton;
	}

	public javax.swing.JTextField getNameField() {
		return threadsField;
	}

	public javax.swing.JTextField getFilenameField() {
		return filenameField;
	}

	public javax.swing.JTextField getaStartField() {
		return aStartField;
	}

	public javax.swing.JTextField getbStartField() {
		return bStartField;
	}

	public javax.swing.JTextField getHeightField() {
		return heightField;
	}

	public javax.swing.JTextField getWidthField() {
		return widthField;
	}

	public JTextField getaEndField() {
		return aEndField;
	}

	public JTextField getbEndField() {
		return bEndField;
	}
	
	public JTextField getThreadsField() {
		return threadsField;
	}

	public void setGenerateButton(javax.swing.JButton generateButton) {
		this.generateButton = generateButton;
	}

	/**
	 * Creates new form Arguments
	 */
	public Arguments() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		widthField = new javax.swing.JTextField();
		filenameField = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		aStartField = new javax.swing.JTextField();
		aStartField.setColumns(10);
		threadsField = new javax.swing.JTextField();
		generateButton = new javax.swing.JButton();
		heightField = new javax.swing.JTextField();
		widthLebel = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		bStartField = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();

		widthField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				widthFieldActionPerformed(evt);
			}
		});

		jLabel4.setText("Filename");

		threadsField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nameFieldActionPerformed(evt);
			}
		});

		generateButton.setText("Generate");
		generateButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				GenerateFractalActionPerformed(evt);
			}
		});

		heightField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sizeField1ActionPerformed(evt);
			}
		});

		widthLebel.setText("Width");

		jLabel5.setText("Height");

		jLabel6.setText("A");

		jLabel7.setText("B");

		JLabel lblGeneralSettings = new JLabel("General settings");

		lblSize = new JLabel("Size:");

		lblInterval = new JLabel("Interval:");

		aEndField = new JTextField();
		aEndField.setColumns(10);

		bEndField = new JTextField();
		bEndField.setColumns(10);

		lblThreads = new JLabel("Threads");
		GroupLayout groupLayout = new GroupLayout(this);
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(10)
					.addComponent(lblSize))
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(21)
					.addComponent(widthLebel)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(widthField, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
					.addGap(20)
					.addComponent(jLabel5)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(heightField, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(10)
					.addComponent(lblInterval))
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(21)
					.addComponent(jLabel6)
					.addGap(10)
					.addComponent(aStartField, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(aEndField, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(21)
					.addComponent(jLabel7)
					.addGap(11)
					.addComponent(bStartField, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(bEndField, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(10)
					.addComponent(lblGeneralSettings))
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(21)
					.addComponent(lblThreads)
					.addGap(12)
					.addComponent(threadsField, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(21)
					.addComponent(jLabel4)
					.addGap(9)
					.addComponent(filenameField, GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
					.addContainerGap())
				.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
					.addGap(72)
					.addComponent(generateButton, GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
					.addContainerGap())
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(groupLayout.createSequentialGroup()
					.addGap(11)
					.addComponent(lblSize)
					.addGap(4)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(widthLebel, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(1)
							.addComponent(widthField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(1)
							.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
								.addComponent(heightField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
					.addGap(18)
					.addComponent(lblInterval)
					.addGap(11)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel6)
						.addComponent(aStartField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(aEndField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(2)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(3)
							.addComponent(jLabel7))
						.addComponent(bStartField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(bEndField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(23)
					.addComponent(lblGeneralSettings)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(3)
							.addComponent(lblThreads))
						.addComponent(threadsField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(5)
							.addComponent(jLabel4))
						.addGroup(groupLayout.createSequentialGroup()
							.addGap(2)
							.addComponent(filenameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addGap(17)
					.addComponent(generateButton)
					.addContainerGap())
		);
		setLayout(groupLayout);
	}// </editor-fold>//GEN-END:initComponents

	private void widthFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_widthFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_widthFieldActionPerformed

	private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_nameFieldActionPerformed

	private void GenerateFractalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GenerateFractalActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_GenerateFractalActionPerformed

	private void sizeField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sizeField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_sizeField1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton generateButton;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JTextField threadsField;
	private javax.swing.JTextField filenameField;
	private javax.swing.JTextField aStartField;
	private javax.swing.JTextField bStartField;
	private javax.swing.JTextField heightField;
	private javax.swing.JTextField widthField;
	private javax.swing.JLabel widthLebel;
	private JLabel lblSize;
	private JLabel lblInterval;
	private JTextField aEndField;
	private JTextField bEndField;
	private JLabel lblThreads;
}
